version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/node_boilerplate
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=node_boilerplate
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge